from __future__ import annotations

import re
from pathlib import Path


def slugify(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return slug or "new-project"


def render_templates(project_name: str) -> dict[str, str]:
    slug = slugify(project_name)
    title = project_name.strip() or "New Project"
    return {
        ".gitignore": "__pycache__/\n.venv/\n.pytest_cache/\ndist/\nbuild/\n",
        "README.md": (
            f"# {title}\n\n"
            "Bootstrap workspace generated by `open-clodex-iflow scaffold`.\n"
            "Fill in the mandatory docs before implementation work.\n"
        ),
        "pyproject.toml": (
            "[build-system]\n"
            'requires = ["setuptools>=68", "wheel"]\n'
            'build-backend = "setuptools.build_meta"\n\n'
            "[project]\n"
            f'name = "{slug}"\n'
            'version = "0.1.0"\n'
            f'description = "Bootstrap workspace for {title}."\n'
            'requires-python = ">=3.11"\n'
        ),
        "Makefile": (
            ".PHONY: check-fast check lint enforce test-unit test-integration scan\n\n"
            "check-fast: lint enforce test-unit\n\n"
            "check: check-fast test-integration scan\n"
        ),
        "TASKS.md": (
            "# TASKS\n\n"
            "## Sources\n\n"
            "- PRD\n- TODO\n- epics\n- stories\n\n"
            "## Readiness\n\n"
            "- scope is bounded\n- verify commands exist\n- docs impact is explicit\n"
        ),
        "TODO.md": "# TODO\n\n- [ ] Fill in PRD\n- [ ] Fill in ARCH_SPEC\n- [ ] Define first epic and story\n",
        "HABIT_TRACKER.md": "# HABIT_TRACKER\n\n| Date | Decision | Follow-up |\n| --- | --- | --- |\n",
        "docs/START_HERE.md": (
            "# START_HERE\n\n"
            "## Sequence\n\n"
            "1. Read READ_FIRST.\n2. Fill docs.\n3. Create epic/story.\n4. Run gates before code.\n"
        ),
        "docs/READ_FIRST.md": (
            "# READ_FIRST\n\n"
            "## Questions\n\n"
            "- What slice is changing?\n- What contract changes?\n- What tests must fail first?\n"
        ),
        "docs/EXECUTION_PRINCIPLES.md": (
            "# EXECUTION_PRINCIPLES\n\n"
            "- Repo docs are source of truth.\n"
            "- Docs must not overclaim runtime.\n"
            "- Enforcement and tests come before feature expansion.\n"
        ),
        "docs/AI_PROJECT_CHECKLIST.md": (
            "# AI_PROJECT_CHECKLIST\n\n"
            "- Scope is bounded.\n- Contracts are explicit.\n- Gates are defined.\n- Docs are synchronized.\n"
        ),
        "docs/PRD.md": f"# PRD\n\n## Goal\n\nBootstrap {title}.\n",
        "docs/ARCH_SPEC.md": "# ARCH_SPEC\n\n## Components\n\n- cli\n- domain\n- enforcement\n",
        "docs/AGENTS.md": "# AGENTS\n\n## Roles\n\n- Human operator\n- Implementer\n- Reviewer\n",
        "docs/SKILLS.md": "# SKILLS\n\n## Required skills\n\n- architecture review\n- testing discipline\n",
        "docs/ORCHESTRATED.md": (
            "# ORCHESTRATED\n\n"
            "## Modes\n\n- `/solo`\n- `/orch`\n\n"
            "## Pattern\n\n- intake\n- preflight\n- fan-out\n- aggregation\n- handback\n"
        ),
        "docs/ARCHITECTURE_BASELINE.md": (
            "# ARCHITECTURE_BASELINE\n\n"
            "## Rules\n\n"
            "- Keep layers separated.\n"
            "- Keep secrets out of the repo.\n"
            "- Keep docs/task artifacts synchronized with runtime truth.\n"
        ),
        "docs/QUALITY_GATES.md": (
            "# QUALITY_GATES\n\n"
            "## Commands\n\n- `make check-fast`\n- `make check`\n\n"
            "## Preconditions\n\n- required docs exist\n- first story exists\n"
        ),
        "docs/JTBD.md": (
            "# JTBD\n\n"
            "## Core jobs\n\n"
            "- Switch between private work and orchestrated review without repeated setup.\n"
            "- Start from an Iron Dome-compatible engineering baseline.\n"
        ),
        f"tasks/epics/epic-1-bootstrap-{slug}.md": (
            f"# Epic 1: Bootstrap {title}\n\n"
            "## Goal\n\nCreate the initial engineering baseline.\n"
        ),
        "tasks/stories/1.1-repo-bootstrap.story.md": (
            "# Story 1.1 - Repo bootstrap\n\n"
            "## 1. Контекст\n\nBootstrap the repository.\n\n"
            "## 2. Outcome\n\nStarter repo exists.\n\n"
            "## 3. Architecture integration\n\nMatches baseline rules.\n\n"
            "## 4. Step-by-step план\n\n1. Create docs.\n2. Create checks.\n\n"
            "## 5. Test cases\n\n- Required files exist.\n\n"
            "## 6. Edge cases\n\n- Re-run scaffold into existing directory.\n\n"
            "## 7. Acceptance criteria\n\n- Starter files exist.\n\n"
            "## 8. Команды проверки\n\n- `make check-fast`\n\n"
            "## 9. Что не делать\n\n- Do not skip the required docs.\n"
        ),
        "enforcement/.gitkeep": "",
        "scripts/.gitkeep": "",
        "tests/unit/.gitkeep": "",
        "tests/integration/.gitkeep": "",
    }


def scaffold_workspace(destination: Path, *, force: bool = False) -> list[Path]:
    destination = destination.resolve()
    if destination.exists() and any(destination.iterdir()) and not force:
        raise FileExistsError(
            f"Destination '{destination}' is not empty. Use --force to overwrite known files."
        )

    created: list[Path] = []
    templates = render_templates(destination.name)
    for relative_path, content in templates.items():
        path = destination / relative_path
        path.parent.mkdir(parents=True, exist_ok=True)
        if path.exists() and not force:
            raise FileExistsError(f"Refusing to overwrite existing file without --force: {path}")
        path.write_text(content, encoding="utf-8")
        created.append(path)

    return created
